FROM hub.yozosoft.com:4431/common/tomcat:9.0.89-jdk8-uuid


RUN set -ex && \
    echo 'Yes, do as I say!'|apt install libtinfo5 && \
    apt-get update && \
    apt install ncurses-base blender ffmpeg ghostscript imagemagick libglu1-mesa-dev -y

ENV PATH=/usr/local/blender-2.79-linux-glibc219-x86_64:$PATH
