FROM chtsen/tomcat:IMAGE_TAG-uuid

RUN set -ex && \
    echo 'Yes, do as I say!'|apt install libtinfo5 && \
    apt-get update && \
    apt install ncurses-base blender ffmpeg ghostscript imagemagick libglu1-mesa-dev -y

ENV PATH=/usr/local/blender-2.79-linux-glibc219-x86_64:$PATH
