FROM chtsen/yozo-tomcat:IMAGE_TAG-uuid-sp

COPY ./tools/redis/redis.conf /opt/yozo/conf/redis/

RUN set -ex && \ 
    apt-get update && \
    apt-get install redis -y && \
    rm -rf  /var/lib/apt/lists/*
