FROM chtsen/yozo-jar:IMAGE_TAG-uuid

COPY --chown=1099:1099 --chmod=755 ./tools/redis/redis.conf /opt/yozo/conf/redis/
COPY --chown=1099:1099 --chmod=755 ./tools/shell/yozo-tomcat/${DCS_V}/entrypoint-aio.sh /opt/yozo/bin/entrypoint.sh

RUN set -ex && \ 
    apt-get update && \
    apt-get install redis -y && \
    rm -rf  /var/lib/apt/lists/*
    
