FROM chtsen/yozo-jar:IMAGE_TAG-uuid

RUN set -ex && \
    apt-get update && \
    #echo 'Yes, do as I say!'|apt install libtinfo5 && \
    apt-get install ncurses-base blender ffmpeg ghostscript imagemagick libglu1-mesa-dev -y && \
    rm -rf  /var/lib/apt/lists/*

# ENV PATH=/usr/local/blender-2.79-linux-glibc219-x86_64:$PATH
