FROM chtsen/yozo-tomcat:IMAGE_TAG-uuid

COPY --chown=1099:1099 --chmod=755 ./tools/redis/redis.conf /opt/yozo/conf/redis/

RUN set -ex && \ 
    apt-get update && \
    apt-get install redis -y && \
    rm -rf  /var/lib/apt/lists/*
    
